# Configurações do Allure Reports - Agibank
allure.results.directory=allure-results
allure.report.directory=allure-report

# Configurações de idioma
allure.language=pt

# Configurações de tema
allure.theme=dark

# Informações do projeto
allure.project.name=consignado
allure.project.description=Automação de Testes do Sistema Consignado

# Configurações de anexos
allure.attachments.include=false

# Configurações de screenshots (controle de duplicatas)
allure.screenshot.include=true
allure.screenshot.on.failure=true
allure.screenshot.on.success=false
allure.screenshot.diff=false
allure.results.cleanup=true

# Configurações de histórico
allure.history.retention.days=30

